# Project: 学生成绩排序
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 学生成绩排序.o
LINKOBJ  = 学生成绩排序.o
LIBS     = -L"D:/Gev-C++/Dev-Cpp/MinGW64/lib" -L"D:/Gev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Gev-C++/Dev-Cpp/MinGW64/include" -I"D:/Gev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Gev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Gev-C++/Dev-Cpp/MinGW64/include" -I"D:/Gev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Gev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Gev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 学生成绩排序.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

学生成绩排序.o: 学生成绩排序.cpp
	$(CPP) -c 学生成绩排序.cpp -o 学生成绩排序.o $(CXXFLAGS)
